version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:45"
      timezone: "Asia/Kolkata"
    assignees:
      - "coolbreeze413"
    #labels:
    #  - "submodule-updates"
    # Must use the full team name, including the organization, as if you were @mentioning the team
    reviewers:
      - "coolbreeze413"
    # Allow dependabot to open up to 10 open pull requests. Default is 5.
    # open-pull-requests-limit: 10
    allow:
      # only enable for the "b" submodule
      - dependency-name: "dependabot_sub_b"
      - dependency-name: "dependabot_sub_a"
